[workspace]
resolver = "3"
members = ["crates/*", "cli/kern"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
kern-text = { path = "crates/kern-text" }
kern-core = { path = "crates/kern-core" }

[profile.release]
lto = "thin"
codegen-units = 1
