[package]
name = "kern-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[lib]
crate-type = ["staticlib"]

[dependencies]
kern-core.workspace = true
kern-search = { version = "0.1.0", path = "../kern-search" }
kern-term = { version = "0.1.0", path = "../kern-term" }
kern-lsp = { version = "0.1.0", path = "../kern-lsp" }
kern-dap = { version = "0.1.0", path = "../kern-dap" }
kern-ext = { version = "0.1.0", path = "../kern-ext" }
kern-vcs = { version = "0.1.0", path = "../kern-vcs" }
swift-bridge = "0.1.59"

[build-dependencies]
swift-bridge-build = "0.1.59"
